// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIWZggctOV4mQ-LLBI0xtzRKUSAMk-8ak',
    appId: '1:934497044642:web:2ac753000dd290f413affb',
    messagingSenderId: '934497044642',
    projectId: 'sustenance-swap',
    authDomain: 'sustenance-swap.firebaseapp.com',
    storageBucket: 'sustenance-swap.appspot.com',
    measurementId: 'G-T2K35PSMKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYVQekmCPdbVnZkIDFYne5L1bSQoB-uYs',
    appId: '1:934497044642:android:b03ed15ddd90a01513affb',
    messagingSenderId: '934497044642',
    projectId: 'sustenance-swap',
    storageBucket: 'sustenance-swap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN0kAfQVMt5CJMG-DlmO6aPWiPJP7DlFw',
    appId: '1:934497044642:ios:04e3673b51af238d13affb',
    messagingSenderId: '934497044642',
    projectId: 'sustenance-swap',
    storageBucket: 'sustenance-swap.appspot.com',
    iosClientId: '934497044642-g1jj14hg0sh1f2lmnufp80l7f50oc94m.apps.googleusercontent.com',
    iosBundleId: 'com.titans.urbansketchers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN0kAfQVMt5CJMG-DlmO6aPWiPJP7DlFw',
    appId: '1:934497044642:ios:427cefb5675b556c13affb',
    messagingSenderId: '934497044642',
    projectId: 'sustenance-swap',
    storageBucket: 'sustenance-swap.appspot.com',
    iosClientId: '934497044642-su11o4bu9s3cco1mng88gseehk86pi2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanSketchers',
  );
}
