// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitl4ZBqTC0P_UDLkzdyFyUJRo6h4VHA8',
    appId: '1:1048441793418:web:f57e7f006b0012bca6f673',
    messagingSenderId: '1048441793418',
    projectId: 'final-project-titans',
    authDomain: 'final-project-titans.firebaseapp.com',
    storageBucket: 'final-project-titans.appspot.com',
    measurementId: 'G-H3SLRWLLYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAatpkoK1_uIUiGpVa6A2HocahKyvZW7Ss',
    appId: '1:1048441793418:android:e11e75981a74b8f1a6f673',
    messagingSenderId: '1048441793418',
    projectId: 'final-project-titans',
    storageBucket: 'final-project-titans.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8MoxnO8qHL5jYJkZhyJeYjZAMkzqbs-4',
    appId: '1:1048441793418:ios:32202290dcfac585a6f673',
    messagingSenderId: '1048441793418',
    projectId: 'final-project-titans',
    storageBucket: 'final-project-titans.appspot.com',
    iosClientId: '1048441793418-rkiqnensjldgpirtd264jrlmupf0vjfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanSketchers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8MoxnO8qHL5jYJkZhyJeYjZAMkzqbs-4',
    appId: '1:1048441793418:ios:32202290dcfac585a6f673',
    messagingSenderId: '1048441793418',
    projectId: 'final-project-titans',
    storageBucket: 'final-project-titans.appspot.com',
    iosClientId: '1048441793418-rkiqnensjldgpirtd264jrlmupf0vjfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.urbanSketchers',
  );
}
